### PR TITLE
fix: update dependencies

### PR DESCRIPTION
**Pull request by Daanvdplas**
error when `cargo install --path .`

### CODE REVIEW

**Review by peterwht — APPROVED** [review]
Manually tested and confirmed that it builds and installs correctly.

**Comment by AlexD10S** [comment]
A `cargo build` works for both of you here? I might have something wrong then, getting 2 errors:

```
error[E0308]: mismatched types
   --> src/engines/contract_engine.rs:76:61
    |
76  |     let instantiate_result = instantiate_exec.instantiate(Some(gas_limit)).await?;
    |                                                           ---- ^^^^^^^^^ expected `sp_weights::weight_v2::Weight`, found `sp_weights::Weight`
```

```
error[E0308]: mismatched types
   --> src/commands/up/contract.rs:128:11
    |
128 |                 .salt(self.salt.clone())
    |                  ---- ^^^^^^^^^^^^^^^^^ expected `sp_core::Bytes`, found a different `sp_core::Bytes`
```

Tried a `cargo clean`, but still

**Comment by weezy20** [comment]
I am getting the same build errors. Why was this merged then?

**Comment by weezy20** [comment]
@AlexD10S pushed a fix #52 please merge.

**Comment by AlexD10S** [comment]
It finally worked for me. Try manually removing `Cargo.lock file, `target` dir and run `cargo build` again

**Pull request merged**
