### PR TITLE
docs: add community section to README

### PR DESCRIPTION
**Pull request by brunopgalvao**
ditto

### CODE REVIEW

**Review by AlexD10S — COMMENTED** [review]
Nice.
But I think is a better idea to add the Telegram and all the links as we have it in the pop network repository: https://github.com/r0gue-io/pop-node

**Comment by brunopgalvao** [comment]
> Nice. But I think is a better idea to add the Telegram and all the links as we have it in the pop network repository: https://github.com/r0gue-io/pop-node

Yes we should add it there as well. Inspiration came from Scio Labs ink!athon repo:
- https://github.com/scio-labs/inkathon?tab=readme-ov-file#inkathon-boilerplate

**Comment by AlexD10S** [comment]
> > Nice. But I think is a better idea to add the Telegram and all the links as we have it in the pop network repository: https://github.com/r0gue-io/pop-node
> 
> Yes we should add it there as well. Inspiration came from Scio Labs ink!athon repo:
> 
> * https://github.com/scio-labs/inkathon?tab=readme-ov-file#inkathon-boilerplate

The Telegram link is in the `pop-node` README. My proposal is to add it here as well, using the same format and including it with the badges there.

**Review by AlexD10S — APPROVED** [review]
Thanks! LGTM

**Pull request merged**
