### PR TITLE
feat(cli): integrate assets parachain template.

### PR DESCRIPTION
**Pull request by al3mart**
This PR substitutes #131.

Asset parachain template moved to: https://github.com/r0gue-io/assets-parachain

### CODE REVIEW

**Review by brunopgalvao — APPROVED** [review]

**Comment by AlexD10S** [comment]
Just a small thing. This is the info when running `pop new parachain --help`:
```
Options:
  -t, --template <TEMPLATE>            Template to use: 'base' for Pop and 'cpt' and 'fpt' for Parity templates
```
Can you add there assets? The code is here: https://github.com/r0gue-io/pop-cli/blob/main/crates/pop-cli/src/commands/new/parachain.rs#L25

**Comment by evilrobot-01** [comment]
> Can you add there assets?

We shouldn't have to update this description with each change like this, it is prone to error. It should be general and should either call a function to generate the list of templates based on available enum variants, or refer to another subcommand to show all accepted values.

Seems that clap has something called `PossibleValue`, so seems that might be the right approach.

**Comment by evilrobot-01** [comment]
Addressed in https://github.com/r0gue-io/pop-cli/pull/133

**Review by evilrobot-01 — APPROVED** [review]
Super clean PR, shows how easy it will be to add templates moving forward.

I would wait until https://github.com/r0gue-io/pop-cli/pull/133 is approved and merged before merging this one.

**Review by AlexD10S — APPROVED** [review]

**Pull request merged**
